// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.Arm;

import org.usfirst.frc3620.Arm.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    
	public static Joystick drive;
	public static JoystickButton moveSDown;
	public static JoystickButton moveSUp;
	public static JoystickButton moveEDown;
	public static JoystickButton moveEUp;
	public static JoystickButton moveTLeft;
	public static JoystickButton moveTRight;
	public static JoystickButton toggleClamp;
	public static JoystickButton toggleUnclamp;
	public static JoystickButton moveWristUp;
	public static JoystickButton moveWristDown;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    	drive = new Joystick(0);
    	moveSDown = new JoystickButton(drive, 4 );
    	moveSDown.whileHeld(new MoveShoulderDown());
    	moveSUp = new JoystickButton(drive, 1);
    	moveSUp.whileHeld(new MoveShoulderUp());
    	moveEDown = new JoystickButton(drive, 3);
    	moveEDown.whileHeld(new MoveElbowDown());
    	moveEUp = new JoystickButton(drive, 2);
    	moveEUp.whileHeld(new MoveElbowUp());
    	moveTLeft = new JoystickButton(drive, 6);
    	moveTLeft.whileHeld(new TwisterLeft());
    	moveTRight = new JoystickButton(drive, 5);
    	moveTRight.whileHeld(new TwisterRight());
    	toggleClamp = new JoystickButton(drive, 9);
    	
    	
    	
    	toggleClamp.whenPressed(new Clamp());
    	toggleUnclamp = new JoystickButton(drive, 10);
    	toggleUnclamp.whenPressed(new Unclamp());
    	moveWristUp = new JoystickButton(drive, 7);
    	moveWristUp.whileHeld(new RotateWristUp());
    	moveWristDown = new JoystickButton(drive, 8);
    	moveWristDown.whileHeld(new RotateWristDown());
    	


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("Move Shoulder Down", new MoveShoulderDown());
        SmartDashboard.putData("Move Shoulder Up", new MoveShoulderUp());
        SmartDashboard.putData("Move Elbow Up", new MoveElbowUp());
        SmartDashboard.putData("Move Elbow Down", new MoveElbowDown());
        SmartDashboard.putData("Move Torso Left", new TwisterLeft());
        SmartDashboard.putData("Move Torso Right", new TwisterRight());
        
        SmartDashboard.putData("Clamp", new Clamp());
        SmartDashboard.putData("Unclamp", new Unclamp());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    public double getWristJoystick() {
    	return drive.getRawAxis(1);
    }
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

