// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3620.Arm;

import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static SpeedController shoulderMotor;
	public static SpeedController elbowMotor;
	public static SpeedController twisterActuator;
	public static Servo wristServo;
	public static DoubleSolenoid Grip; 
	

    public static void init() {
        shoulderMotor = new Spark(1);
        LiveWindow.addActuator("armSubsystem","shoulderMotor", (Spark) shoulderMotor);
        
        elbowMotor = new Spark(2);
        LiveWindow.addActuator("armSubsystem", "elbowMotor", (Spark) elbowMotor);
        
        twisterActuator = new Spark(0);
        LiveWindow.addActuator("armSubsystem", "twisterActuator", (Spark) twisterActuator);
        
        wristServo = new Servo(9);
        LiveWindow.addActuator("armSubsystem", "wristServo", wristServo);
        
        Grip = new DoubleSolenoid(0,0,1);
        LiveWindow.addActuator("armSubsystem", "Gripper", Grip);
        
    }
}
